# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60cfcdc2c22c33740deaf5e38c4887f6d5224cf1eda030fbf7e1fac7a10b865495ac0315906b73617e3ec4996961fb3aa12147a5c43b21d3a841b906b1b78e8e

test:
  secret_key_base: 25047bc84624f35c1a2ee9e03e7b13cd04e8f23b3ac00d52828a5daec1acafd7848cdce9e7f4a81ca9c5d4e2415b8267c4548db5b484088e8210a8b92ceffdef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
